# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89b6c816e397b5a26ae1071f941e4116faf16eb468ad5c4e1d58cf94b76ff51d79d7a144287cf8368141deea982fe33f050154e11836daae60c4ed68c93ef63d

test:
  secret_key_base: 85b836d88a2e3569791bf3a3260e93033bb7887683380baf4dfc91805aebd46f77d37054091b6b7ac834ea9950420163dc4e966dc10491485337905339883888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
